server {
    listen 80;
    server_name _;

    location /alumnos/ {
        alias /var/www/html/alumnos/;
        index index.html;
        try_files $uri $uri/ /alumnos/index.html;
    }

    location /alumnos {
        return 301 /alumnos/;
    }

    location ~ ^/alumnos/(lista|asignaturas|inscribir) {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ~ ^/alumnos/[0-9]+/notas {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
